# Generated by Django 5.2.7 on 2025-11-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_artpiece_date_alter_artpiece_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='art_piece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='portfolio.artpiece'),
        ),
    ]
