# Generated by Django 5.2.7 on 2025-11-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('full_pic', models.ImageField(upload_to='')),
                ('preview_pic', models.ImageField(upload_to='')),
                ('medium', models.CharField(max_length=64)),
                ('dimensions', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='portfolio.artpiece')),
            ],
        ),
    ]
