# Generated by Django 5.2.7 on 2025-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_artpiece_full_pic_alter_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='preview_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
