# Generated by Django 5.2.7 on 2025-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_artpiece_preview_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='dimensions',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='medium',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='description',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
