# Generated by Django 5.2.7 on 2025-11-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_description_art_piece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='picture',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='description',
            name='art_piece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='portfolio.artpiece'),
        ),
    ]
